name: CI - Testes e Validação

on:
  pull_request:
    branches: [ "main" ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer o Checkout do código
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Executar os 5 testes unitários
      run: python -m unittest test_calculadora.py